// <auto-generated />
using System;
using Livraria.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191128003113_lalala")]
    partial class lalala
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Livraria.Models.Categories", b =>
                {
                    b.Property<string>("IdCategories")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemsId");

                    b.Property<string>("categories");

                    b.HasKey("IdCategories");

                    b.HasIndex("ItemsId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Livraria.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<string>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<int?>("EnderecoId");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<string>("Telefone");

                    b.HasKey("ClienteId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Livraria.Models.DevolucaoLivro", b =>
                {
                    b.Property<int>("IdDevolucaoLivro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId");

                    b.Property<int?>("LivroIdLivro");

                    b.HasKey("IdDevolucaoLivro");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LivroIdLivro");

                    b.ToTable("DevolucaoLivros");
                });

            modelBuilder.Entity("Livraria.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Uf");

                    b.Property<string>("endereco");

                    b.HasKey("EnderecoId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Livraria.Models.Items", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvarageRating");

                    b.Property<int?>("LivroIdLivro");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Volume");

                    b.Property<string>("volumeInfoIdTittle");

                    b.HasKey("Id");

                    b.HasIndex("LivroIdLivro");

                    b.HasIndex("volumeInfoIdTittle");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Livraria.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PageCoutn");

                    b.HasKey("IdLivro");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("Livraria.Models.ReservaLivro", b =>
                {
                    b.Property<int>("IdReservaLivro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<DateTime>("DataDevolucaoLivro");

                    b.Property<DateTime>("DataReservaLivro");

                    b.Property<int>("LivroId");

                    b.HasKey("IdReservaLivro");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LivroId");

                    b.ToTable("ReservaLivros");
                });

            modelBuilder.Entity("Livraria.Models.VolumeInfo", b =>
                {
                    b.Property<string>("IdTittle")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("PublishedDate");

                    b.Property<string>("Publisher");

                    b.Property<string>("Title");

                    b.HasKey("IdTittle");

                    b.ToTable("VolumeInfo");
                });

            modelBuilder.Entity("Livraria.Models.Categories", b =>
                {
                    b.HasOne("Livraria.Models.Items")
                        .WithMany("categories")
                        .HasForeignKey("ItemsId");
                });

            modelBuilder.Entity("Livraria.Models.Cliente", b =>
                {
                    b.HasOne("Livraria.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");
                });

            modelBuilder.Entity("Livraria.Models.DevolucaoLivro", b =>
                {
                    b.HasOne("Livraria.Models.Cliente", "Cliente")
                        .WithMany("DevolucaoLivro")
                        .HasForeignKey("ClienteId");

                    b.HasOne("Livraria.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroIdLivro");
                });

            modelBuilder.Entity("Livraria.Models.Items", b =>
                {
                    b.HasOne("Livraria.Models.Livro")
                        .WithMany("items")
                        .HasForeignKey("LivroIdLivro");

                    b.HasOne("Livraria.Models.VolumeInfo", "volumeInfo")
                        .WithMany()
                        .HasForeignKey("volumeInfoIdTittle");
                });

            modelBuilder.Entity("Livraria.Models.ReservaLivro", b =>
                {
                    b.HasOne("Livraria.Models.Cliente", "Cliente")
                        .WithMany("ReservaLivro")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Livraria.Models.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
